# Generated by Django 5.0.14 on 2025-04-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.TextField()),
                ('id_publicacion_ted', models.TextField(blank=True)),
                ('organo_contratacion', models.TextField()),
                ('id_organo_contratacion', models.TextField()),
                ('estado_licitacion', models.TextField()),
                ('objeto_contrato', models.TextField()),
                ('financiacion_ue', models.TextField()),
                ('presupuesto_base_licitacion', models.TextField()),
                ('valor_estimado_contrato', models.TextField()),
                ('tipo_contrato', models.TextField()),
                ('codigo_cpv', models.TextField()),
                ('lugar_ejecucion', models.TextField()),
                ('sistema_contratacion', models.TextField()),
                ('procedimiento_contratacion', models.TextField()),
                ('tipo_tramitacion', models.TextField()),
                ('metodo_presentacion_oferta', models.TextField()),
                ('resultado', models.TextField()),
                ('adjudicatario', models.TextField()),
                ('num_licitadores_presentados', models.TextField()),
                ('importe_adjudicacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
