# Generated by Django 5.0.14 on 2025-05-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacion',
            name='analisis_proyecto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='criterio_ecónomico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='criterio_juicio_val',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='evaluables_autom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='memoria_constructiva',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='precio_unit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='programa_trabajos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='tanto_alzado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='tanto_alzado_con',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='adjudicatario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='codigo_cpv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='estado_licitacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='financiacion_ue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='id_organo_contratacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='id_publicacion_ted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='importe_adjudicacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='lugar_ejecucion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='metodo_presentacion_oferta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='num_licitadores_presentados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='objeto_contrato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='organo_contratacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='presupuesto_base_licitacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='procedimiento_contratacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='resultado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='sistema_contratacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='tipo_contrato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='tipo_tramitacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='valor_estimado_contrato',
            field=models.TextField(blank=True, null=True),
        ),
    ]
